version: 2

defaults: &defaults
  working_directory: ~/repo
  environment:
    LC_ALL: C.UTF-8

install_hex_rebar: &install_hex_rebar
  run:
    name: Install hex and rebar
    command: |
      mix local.hex --force
      mix local.rebar --force

install_system_deps: &install_system_deps
  run:
    name: Install system dependencies
    command: |
        apk add build-base linux-headers

jobs:
  build_elixir_1_11_otp_23:
    docker:
      - image: hexpm/elixir:1.11.2-erlang-23.1.2-alpine-3.12.1
    <<: *defaults
    steps:
      - checkout
      - <<: *install_system_deps
      - <<: *install_hex_rebar
      - restore_cache:
          keys:
            - v1-mix-cache-{{ checksum "mix.lock" }}
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix compile
      - run: mix hex.build
      - run: mix test
      - run: mix docs
      - run: mix dialyzer
      - save_cache:
          key: v1-mix-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps

  build_elixir_1_10_otp_23:
    docker:
      - image: hexpm/elixir:1.10.4-erlang-23.1.2-alpine-3.12.1
    <<: *defaults
    steps:
      - checkout
      - <<: *install_system_deps
      - <<: *install_hex_rebar
      - run: mix deps.get
      - run: mix compile
      - run: mix test

  build_elixir_1_9_otp_22:
    docker:
      - image: hexpm/elixir:1.9.4-erlang-22.3.4.9-alpine-3.12.0
    <<: *defaults
    steps:
      - checkout
      - <<: *install_system_deps
      - <<: *install_hex_rebar
      - run: mix deps.get
      - run: mix compile
      - run: mix test

  build_elixir_1_8_otp_22:
    docker:
      - image: hexpm/elixir:1.8.2-erlang-22.3.4.9-alpine-3.12.0
    <<: *defaults
    steps:
      - checkout
      - <<: *install_system_deps
      - <<: *install_hex_rebar
      - run: mix deps.get
      - run: mix compile
      - run: mix test

  build_elixir_1_7_otp_21:
    docker:
      - image: hexpm/elixir:1.7.4-erlang-21.3.8.15-alpine-3.12.0
    <<: *defaults
    steps:
      - checkout
      - <<: *install_system_deps
      - <<: *install_hex_rebar
      - run: mix deps.get
      - run: mix test

workflows:
  version: 2
  build_test:
    jobs:
      - build_elixir_1_11_otp_23:
          context: org-global
      - build_elixir_1_10_otp_23:
          context: org-global
      - build_elixir_1_9_otp_22:
          context: org-global
      - build_elixir_1_8_otp_22:
          context: org-global
      - build_elixir_1_7_otp_21:
          context: org-global
